### ISSUE TITLE
Does these work with pouchjs?

### ISSUE THREAD

**Issue by hugotai101** [anuragvohraec/dartJSEngine#2]
I saw u were trying to use pouchjs in flutter, does it works well? what is your solution now?

**Comment by anuragvohraec** [comment]
I think I am too late to reply.
I ultimately gave up on flutter: [Reason for breakup](https://dev.to/anuragvohraec/breaking-up-with-flutter-getting-along-with-pwa-4fic)

Regarding pouchjs, it won't work. As pouch JS needs indexedDB apis.
This is just a JSEngine, indexedDB is part web api specification.
You can only execute JS code in it, web apiwon't be available in it. (for example node js too do not have indexeddb APIs in it)
